### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by LlamaDrama-lab** [fcamarlinghi/cepy#2]
I got this message:

> expresso@1.0.0 exporter:release C:\Users\User\Desktop\expresso
> node bin/build.js exporter release

C:\Users\User\Desktop\expresso\node_modules\cepy\cepy.js:120
Cepy.prototype.launch = function (buildName, product, family, debug)
^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:607:28)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\User\Desktop\expresso\scripts\tasks\exporter.js:9:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! expresso@1.0.0 exporter:release: `node bin/build.js exporter release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the expresso@1.0.0 exporter:release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by fcamarlinghi** [comment]
Sorry about that, forgot to commit a change. Should be fixed now; if not, let me know. Cheers.
